### ISSUE TITLE
Dressingrooms UI Prefab suddenly warped (and broken)

### ISSUE THREAD

**Issue by ransell** [leodenault/fashion#10]
Noticed it when I opened Unity this morning (after rolling back the scroll barrier push last night).

When you click on a shopkeeper, it opens up the dressingroom. The dressingroom background is the right size, but the camera and all the UI elements (from the Shop UI prefab) are warped with the camera. I can't figure out how to change it. :(

**Comment by leodenault** [comment]
- The bug is caused by a typo in your clothing XML file for the Sandal Heels entry. The image path is "clothing/preppyy/..." when it should be "clothing/preppy/...". Essentially, remove the extra "y" in "preppyy".
- Since this bug only affects you locally due to your own local changes, I'm going to change the status of this bug to Invalid.
